### ISSUE TITLE
Why two passes?

### ISSUE THREAD

**Issue by steinitznavican** [data61/foldl-statistics#7]
You can compute the count, mean and second moment in one pass so I am puzzled as to why the documentation states it has to be two?

**Comment by axman6** [comment]
This is what the `fast*` functions do, but some of the more numerically accurate algorithms require knowing the mean before computing the central moments. The README and probably a lot of the rest of the package probably needs updating.

**Comment by steinitznavican** [comment]
I discovered the fast functions after I posted the question. Sorry for the noise.
